src/cometbft.rs
src/command/archive.rs
src/command/regen.rs
src/penumbra.rs
src/penumbra/v0o79.rs
src/penumbra/v0o80.rs
src/storage.rs

This now stores the chain id in the archive file, and checks that:
- it matches if already present when running any archival state,
- it matches the penumbra rocksdb state when regenerating, if such a state exists.
Closes #6.

Implement robust chain id checking

---

src/command/archive.rs
src/indexer.rs
src/storage.rs

This makes both database handles close on drop, to flush anything not flushed, and this removes the unnecessary concurrency in the archive command causing some of the blocks to not get put there.

Make archival code more robust

---

.envrc.example
.github/workflows/rust.yml
.gitignore
Cargo.toml
build.rs
flake.lock
flake.nix
justfile
src/storage.rs

First pass at a dev env, which pulls in the usual Rust deps, as well as go, which is required to build `penumbra-indexer`. The devshell pulls in the necessary deps, resulting in `cargo build` running the proxy build for go via `build.rs` just fine.
Not yet supported is `nix build`: will need to figure out a two-pass approach, because network access during the buildPhase is not permitted, so the go build via rust fails.
Closes #4.

ci: add nix env and gha workflows

---

Cargo.lock
Cargo.toml

For the v0.80.x release series, we're now on `v0.80.6`, and for v0.79.x, bumped to `v0.79.5`. See corresponding release issues:
* https://github.com/penumbra-zone/penumbra/issues/4882
* https://github.com/penumbra-zone/penumbra/issues/4876
I also sorted the deps to make them a bit more readable and easier to manage.

chore: bump penumbra deps to v0.80.6

---

.github/workflows/build.yml
.gitignore
build.rs
flake.nix

The existing `build.rs` script assumes that go has been set up sufficiently, and calls out to it to build the static library for cometbft for linking against. That's rad, but naively calling out to `go build` from inside `nix build` fails, because the rust overlay doesn't know anything about golang, and forbids arbitrary network calls.
Instead, we'll have to be explicit about preparing the `libcomebft.a` static lib as a discrete output, and consuming it as an input in the rust build. We can do so by opting in to using a prebuilt lib via env var in the `build.rs` script.
This change improves the nix config, making it sufficiently defined to perform a `nix build` successfully. Careful attention was given to preserving the existing functionality so that `cargo build` will still do the right …

build: support 'nix build' for cometbft archive

---

Cargo.lock
Cargo.toml

This is the most recent release in the v0.80.x series. Also increments the `penumbra-reindexer` version, 0.1.0 -> 0.1.1, to disambiguate.

chore: bump penumbra deps to v0.80.11

---

Cargo.lock
Cargo.toml
README.md
src/penumbra.rs
src/penumbra/v0o81.rs

Adds support for the `v0.80.x` -> `v0.81.x` chain upgrade for the `penumbra-1` chain.
1. Use a preexisting `reindexer_archive.bin`, or obtain from https://artifacts.plinfra.net/: the one marked `reindexer_archive-height-2609670.sqlite` would be great because it's right before the target upgrade height that we're adding support for.
2. Use an up-to-date node state dir to update the archive: `systemctl stop penumbra cometbft && penumbra-reindexer archive`
3. Ideally, target a fresh database and run `penumbra-reindexer archive [...]` to write to it. That'll take a while, ~20h or so.

feat: add support for penumbra v0.81.x

---

build.rs

This avoids relying on `libresolv` and fixes #19.

reindexer: use the pure-go resolver

---

src/penumbra.rs

This also adds a plan for the testnet.
Closes #23.

Dynamically choose which plan to run based on archive chain id

---

src/penumbra.rs
src/storage.rs

This can help prevent some potential mistakes in creating a plan, by checking that for the steps of the plan, the first and last blocks that it needs are present, and that any genesis it needs is also present. This can prevent off by one mistakes around upgrades in particular, since the genesis won't exist.

Implement safeguards to check plan against the archive

---

CHANGELOG.md
Cargo.lock
Cargo.toml

I've been bumping the version routinely to ensure the proper versions are used on the relevant nodes. Also adds a changelog, to keep things organized.

chore: bump version to 0.1.3

---

Cargo.toml
justfile
src/lib.rs
src/tendermint_compat.rs
tests/common/mod.rs
tests/file.rs

This fixes a couple issues we missed in the conversion from v040 begin blocks to v034 begin blocks.
This also adds a testing harness which reads all the blocks in an archive, and tests that it's convertible to both types.
This can be run with:
```
cargo test --features expensive-tests --test file '' -- ~/Downloads/reindexer_archive-height-1703224.sqlite
```
replacing the archive file appropriately.
(In the near future I'd like to refactor some of the expensive tests to be under a common feature flag, and take parameters on the command line like this, but that can wait).
Closes #34. (We should check that there aren't other issues, the other types require actually interacting with the simulated penumbra nodes, and I haven't had time to run a reindex yet)

Fix parsing bugs in begin block

---

tests/common/mod.rs
tests/penumbra_1.rs

Each upgrade boundary comes with its own notion of a genesis. For some archives the appropriate genesis file may be bundled in, but other archives only contain `pd/rocksdb/` and `cometbft/data/` dirs. We'll fetch the appropriate genesis file based on the phase during setup of the archive data.
Closes #37.

fix(tests): fetch matching genesis per phase

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Just a bit of housekeeping, to help keeping versions straight on the machines I manage.

chore: release penumbra-reindexer version 0.2.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml

We want to update the dependencies to support the newly added event for parameter changes, which is currently being reviewed, and ported across the three different tips we maintain.
Leaving this as a draft until those are tagged, but this allows us to test that reindexing will work.

feat: add support for app param change event

---

Cargo.lock
Cargo.toml
src/penumbra.rs
src/penumbra/v1o3.rs
src/penumbra/v1o4.rs

Closes #44.
Looking at this code, I feel like maybe a sem ver bump was warranted, but we can adjust this later.
Unfortunately, we have to use git dependencies because Cargo can only ever have one version of a given package.

Implement latest mainnet migration

---

src/cometbft.rs
src/cometbft/remote.rs
src/command/regen.rs
src/penumbra.rs
src/storage.rs

Now, regen takes an optional `--follow` argument. When this is set to a remote RPC, regeneration can continue past the end of the archive, using the remote store to fetch new blocks, and populate the archive on the side.

Allow regen to follow a remote node

---

src/indexer.rs
src/indexer/schema.sql
src/penumbra.rs
src/penumbra/v0o79.rs
src/penumbra/v0o80.rs
src/penumbra/v1o3.rs
src/penumbra/v1o4.rs
src/penumbra/v2.rs

This is very useful for debugging, since we can pin point exact points where reindexing processes diverge.

Add logging of app hashes to the indexing database

---

Cargo.lock
Cargo.toml
src/command/regen.rs
src/penumbra.rs

This adds a plan for the new testnet, and also makes it so that you can run:
```
penumbra-reindexer regen --working-dir ... --archive-file ... --database-url ... --follow ...
```
with an empty working directory, archive file, and a database that has merely been created, and automatically download the genesis and all the blocks from the new testnet, put them in an archive, and then regenerate the events with the output state in the working directory.
There were a few changes needed to make this work, basically omissions in the following logic that only got exercised now that we have a completely blank slate, rather than an existing archive.

Support testnet phobos 3 + some fixes to following a new testnet

---

.github/workflows/build.yml
.github/workflows/container.yml
.github/workflows/rust.yml
flake.nix
justfile

Adds a container image to the repo CI. Rather than write a Containerfile from scratch, I'm leaning on the already explicitly declared nix build logic, and using that to construct the container image. Tossed in a few nice-to-haves like `curl` and `tar` and friends, which are enough to get started. 
Closes #50.

build: add container image

---

src/command.rs
src/command/export.rs
src/lib.rs

This is useful for getting a genesis out of an archive file.
Usage:
```
Export the genesis file for a specific height
Usage: penumbra-reindexer export genesis --output-file <OUTPUT_FILE> --archive-file <ARCHIVE_FILE> <HEIGHT>
Arguments:
<HEIGHT>  The block height to export the genesis for
Options:
-o, --output-file <OUTPUT_FILE>    Output file to write the genesis to
--archive-file <ARCHIVE_FILE>  Path to the archive file to read from
-h, --help                         Print help
```

Add export genesis <HEIGHT> command

---

src/command/regen.rs
src/indexer.rs
src/indexer/schema.sql

Adds `--allow-existing-data`, which will allow the regenerating indexer to skip indexing existing data, in a way which nonetheless allows filling in any missing data. The idea is that this allows a regenerating process to "lag behind" an actual node, which acts as a primary source of event data, in order to act as a secondary source which focuses on guaranteeing data robustness.
I tested this by regnerating against the current testnet. When running with a new state, but the same events database, the command works as expected, successfully catching up without crashing because of uniqueness constraints, and then can index events after it reaches new data.

Add flag to allow existing data when regenerating

---

Cargo.lock
Cargo.toml

Updates the penumbra deps to the latest backport releases. We initially added support for chain param changes back in https://github.com/penumbra-zone/reindexer/pull/33, but the pd implementation was incomplete. This change bumps all historical version so that a full chain reindex will emit the necessary events.
Refs https://github.com/penumbra-zone/penumbra/issues/5186, https://github.com/penumbra-zone/penumbra/issues/5192

chore: bump penumbra deps for AppVersion fix

---

Cargo.lock
Cargo.toml

This change makes it possible to write a dest database over a TLS connection. Generally speaking doing so is a lot slower than writing directly to a localhost connection, but given the introduction of the "follow" mode from #43, it makes more sense now.

fix: add support for tls db connections

---

Cargo.lock
Cargo.toml

Bumps the testnet/LQT deps to v2.0.0-alpha.11 [0]. Bumps the mainnet/v1 deps to v1.5.2 [1].
[0] https://github.com/penumbra-zone/penumbra/issues/5010
[1] https://github.com/penumbra-zone/penumbra/issues/5203

chore: update penumbra deps

---

Cargo.lock
Cargo.toml
justfile
src/check.rs
src/cometbft/remote.rs
src/command.rs
src/command/archive.rs
src/command/bootstrap.rs
src/command/check.rs
src/command/regen.rs
src/files.rs
src/history.rs
src/history/node.rs
src/history/reindexer.rs
src/lib.rs
src/main.rs
src/penumbra.rs
tests/common/mod.rs
tests/file.rs

This PR adds two (2) new subcommands:
* `penumbra-reindexer bootstrap`
* `penumbra-reindexer check`
The `bootstrap` command will fetch a remote sqlite3 db for a specific chain id. Gzipped compressed archives are supported, since that cuts filesize nearly in half. The `check` command will run a handful of healthchecks against a local db. In both cases, the bulk of the logic is pulled up from the integration tests (https://github.com/penumbra-zone/reindexer/pull/28) into the tool itself, so that operators can leverage the actions.
Significantly, :rotating_light:  **there are breaking changes to filepaths** :rotating_light::  there's now a `~/.local/share/penumbra-reindexer/` home directory for the reindexer, inside which downloaded archives will be stored. The default path for a reindexer …

feat: bootstrap mode
